apiVersion: v1
kind: Service
metadata:
  labels:
    app: mavenapp
  name: mavenapp
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: mavenapp
